// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Ingredient struct {
	ID       string    `json:"id"`
	Name     string    `json:"name"`
	Quantity string    `json:"quantity"`
	Recipe   []*Recipe `json:"recipe"`
}

type Instruction struct {
	ID     string    `json:"id"`
	Info   string    `json:"info"`
	Recipe []*Recipe `json:"recipe"`
}

type Login struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type NewRecipe struct {
	Name string `json:"name"`
}

type NewUser struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Email    string `json:"email"`
}

type Recipe struct {
	ID           string         `json:"id"`
	Name         string         `json:"name"`
	Ingredients  []*Ingredient  `json:"ingredients"`
	Instructions []*Instruction `json:"instructions"`
}

type RecipeIngredient struct {
	Name     string `json:"name"`
	Quantity string `json:"quantity"`
}

type RecipeInstruction struct {
	Info string `json:"info"`
}

type RefreshTokenInput struct {
	Token string `json:"token"`
}
